### ISSUE TITLE
AttributeError: 'VGG' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Riyasharma-in** [dani0105/ai-face-analysis#1]
Traceback (most recent call last):
  File "/home/dl_machine_3/Ria/SER/ai-face-analysis/vgg19-face-expression/predict.py", line 45, in <module>
    net.load_state_dict(checkpoint['net'])
  File "/home/dl_machine_3/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1470, in load_state_dict
    state_dict = state_dict.copy()
  File "/home/dl_machine_3/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VGG' object has no attribute 'copy'

**Comment by dani0105** [comment]
there could be problem with the model file. I'll give you a Google Colab of VGG code and an already trained model
Colab: [link]( https://colab.research.google.com/drive/1KXdnJ3NlDLRG6Km1HX4nOGHKZ-VSR7aH?usp=drive_link)
Model: [link](https://drive.google.com/file/d/1n9H-uE5-R2a6RA-i4vWY588Asjot7-Bj/view?usp=sharing)

I also want to share another VGG colab with you, maybe this will have better results [link](https://colab.research.google.com/drive/1jSIcNKS2dn7QEWbZgs9K5QNvrkLgQGpg)

I hope this helps 😄
